<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed Admin Users
        DB::table('users')->updateOrInsert(
            ['email' => 'admin@bikroybd24.com'],
            [
                'id' => 'u_admin_bikroy',
                'name' => 'BikroyBD24 Admin',
                'email' => 'admin@bikroybd24.com',
                'phone' => '01854288311',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );

        DB::table('users')->updateOrInsert(
            ['email' => 'admin@nexacart.com.bd'],
            [
                'id' => 'u_admin_nexacart',
                'name' => 'Super Admin',
                'email' => 'admin@nexacart.com.bd',
                'phone' => '01700000000',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );

        // 2. Seed Categories
        $categories = [
[
                'id' => 'smartphones-gadgets',
                'name' => 'Smartphones & Audio',
                'slug' => 'smartphones-gadgets',
                'count' => '3,240+ Items',
                'items_count' => '3,240+',
                'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-blue-50 text-blue-700 border-blue-200',
                'desc' => 'Flagship smartphones, iPhones, and wireless audio gear',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'laptops-computers',
                'name' => 'Laptops & Computers',
                'slug' => 'laptops-computers',
                'count' => '1,890+ Items',
                'items_count' => '1,890+',
                'image' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-indigo-50 text-indigo-700 border-indigo-200',
                'desc' => 'MacBooks, gaming laptops, monitors, and peripherals',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'mens-fashion',
                'name' => 'Men\'s Fashion',
                'slug' => 'mens-fashion',
                'count' => '2,540+ Items',
                'items_count' => '2,540+',
                'image' => 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-purple-50 text-purple-700 border-purple-200',
                'desc' => 'Trendy T-shirts, formal wear, Panjabi, and footwear',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'womens-fashion',
                'name' => 'Women\'s Fashion',
                'slug' => 'womens-fashion',
                'count' => '2,890+ Items',
                'items_count' => '2,890+',
                'image' => 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-pink-50 text-pink-700 border-pink-200',
                'desc' => 'Sarees, three-piece, designer handbags, and jewelry',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'home-kitchen',
                'name' => 'Home & Appliances',
                'slug' => 'home-kitchen',
                'count' => '1,420+ Items',
                'items_count' => '1,420+',
                'image' => 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-emerald-50 text-emerald-700 border-emerald-200',
                'desc' => 'Kitchen appliances, cookware, and home decor',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'beauty-care',
                'name' => 'Beauty & Personal Care',
                'slug' => 'beauty-care',
                'count' => '1,150+ Items',
                'items_count' => '1,150+',
                'image' => 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-rose-50 text-rose-700 border-rose-200',
                'desc' => 'Skincare, cosmetics, perfumes, and personal care',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'groceries',
                'name' => 'Groceries & Daily Needs',
                'slug' => 'groceries',
                'count' => '4,500+ Items',
                'items_count' => '4,500+',
                'image' => 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-teal-50 text-teal-700 border-teal-200',
                'desc' => 'Fresh food, essential groceries, and daily supplies',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'smartwatches-audio',
                'name' => 'Smartwatches & Audio',
                'slug' => 'smartwatches-audio',
                'count' => '1,280+ Items',
                'items_count' => '1,280+',
                'image' => 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-cyan-50 text-cyan-700 border-cyan-200',
                'desc' => 'Smartwatches, fitness bands, and bluetooth audio',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ],
[
                'id' => 'sports',
                'name' => 'Sports & Fitness',
                'slug' => 'sports',
                'count' => '640+ Items',
                'items_count' => '640+',
                'image' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&auto=format&fit=crop&q=80',
                'color' => 'bg-amber-50 text-amber-700 border-amber-200',
                'desc' => 'Fitness equipment, sportswear, and active accessories',
                'active' => true,
                'showInTopCategories' => true,
                'showInSidebar' => true,
                'type' => 'main',
                'level' => 'main'
            ]
        ];

        foreach ($categories as $cat) {
            DB::table('categories')->updateOrInsert(['id' => $cat['id']], array_merge($cat, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }

        // 3. Seed Products
        $products = [
[
                'id' => 'f1',
                'sku' => 'SKU-SMAR-001',
                'barcode' => '880910000001',
                'name' => 'Anker Soundcore Motion+ Bluetooth Speaker',
                'title' => 'Anker Soundcore Motion+ Bluetooth Speaker',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 8490,
                'supplierCost' => 5519,
                'oldPrice' => 11500,
                'original_price' => 11500,
                'discount' => 26,
                'rating' => 4.9,
                'reviews' => 184,
                'image' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
                'inStock' => 8,
                'stock' => 8,
                'totalStock' => 30,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 1,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Hi-Res 30W audio with Qualcomm aptX HD and IPX7 waterproof casing.'
            ],
[
                'id' => 'f2',
                'sku' => 'SKU-SMAR-002',
                'barcode' => '880910000002',
                'name' => 'Smart OLED Fitness Watch Series 9',
                'title' => 'Smart OLED Fitness Watch Series 9',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 4250,
                'supplierCost' => 2763,
                'oldPrice' => 6200,
                'original_price' => 6200,
                'discount' => 31,
                'rating' => 4.8,
                'reviews' => 215,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
                'inStock' => 12,
                'stock' => 12,
                'totalStock' => 45,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Real-time SpO2 monitoring, ECG tracking, and 10-day battery stamina.'
            ],
[
                'id' => 'f3',
                'sku' => 'SKU-FASH-003',
                'barcode' => '880910000003',
                'name' => 'Men Ultra-Soft Cotton Polo T-Shirt',
                'title' => 'Men Ultra-Soft Cotton Polo T-Shirt',
                'category' => 'mens-fashion',
                'category_id' => 'mens-fashion',
                'categoryName' => 'Men\'s Fashion',
                'price' => 1250,
                'supplierCost' => 813,
                'oldPrice' => 1850,
                'original_price' => 1850,
                'discount' => 32,
                'rating' => 4.7,
                'reviews' => 96,
                'image' => 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80',
                'inStock' => 15,
                'stock' => 15,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Breathable Pima cotton blend with reinforced collar and tailored fit.'
            ],
[
                'id' => 'f4',
                'sku' => 'SKU-BEAU-004',
                'barcode' => '880910000004',
                'name' => 'L\'Oréal Hydra Genius Daily Moisturizer',
                'title' => 'L\'Oréal Hydra Genius Daily Moisturizer',
                'category' => 'beauty-care',
                'category_id' => 'beauty-care',
                'categoryName' => 'Beauty & Personal Care',
                'price' => 1650,
                'supplierCost' => 1073,
                'oldPrice' => 2250,
                'original_price' => 2250,
                'discount' => 27,
                'rating' => 4.8,
                'reviews' => 142,
                'image' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
                'inStock' => 9,
                'stock' => 9,
                'totalStock' => 40,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Aloe water infusion providing 72 hours of continuous skin hydration.'
            ],
[
                'id' => 'f5',
                'sku' => 'SKU-SMAR-005',
                'barcode' => '880910000005',
                'name' => 'Wireless Active Noise-Canceling Headphones',
                'title' => 'Wireless Active Noise-Canceling Headphones',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 3850,
                'supplierCost' => 2503,
                'oldPrice' => 5500,
                'original_price' => 5500,
                'discount' => 30,
                'rating' => 4.8,
                'reviews' => 178,
                'image' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
                'inStock' => 5,
                'stock' => 5,
                'totalStock' => 25,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Deep bass drivers with dual beamforming mic for crystal clear calls.'
            ],
[
                'id' => 'f6',
                'sku' => 'SKU-HOME-006',
                'barcode' => '880910000006',
                'name' => 'Stainless Steel Electric Kettle 1.8L',
                'title' => 'Stainless Steel Electric Kettle 1.8L',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 2150,
                'supplierCost' => 1398,
                'oldPrice' => 3100,
                'original_price' => 3100,
                'discount' => 30,
                'rating' => 4.7,
                'reviews' => 110,
                'image' => 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?auto=format&fit=crop&w=600&q=80',
                'inStock' => 11,
                'stock' => 11,
                'totalStock' => 40,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Rapid 1500W boil tech with auto shut-off and boil-dry safety protection.'
            ],
[
                'id' => 'f7',
                'sku' => 'SKU-ELEC-007',
                'barcode' => '880910000007',
                'name' => 'Fast Charging Dual USB Power Adapter 65W',
                'title' => 'Fast Charging Dual USB Power Adapter 65W',
                'category' => 'smartphones-gadgets',
                'category_id' => 'smartphones-gadgets',
                'categoryName' => 'Smartphones & Audio',
                'price' => 1950,
                'supplierCost' => 1268,
                'oldPrice' => 2800,
                'original_price' => 2800,
                'discount' => 30,
                'rating' => 4.9,
                'reviews' => 205,
                'image' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
                'inStock' => 14,
                'stock' => 14,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'GaN III technology fast charger for laptops, tablets, and smartphones.'
            ],
[
                'id' => 'f8',
                'sku' => 'SKU-FASH-008',
                'barcode' => '880910000008',
                'name' => 'Men Slim Fit Cotton Chino Trousers',
                'title' => 'Men Slim Fit Cotton Chino Trousers',
                'category' => 'mens-fashion',
                'category_id' => 'mens-fashion',
                'categoryName' => 'Men\'s Fashion',
                'price' => 1850,
                'supplierCost' => 1203,
                'oldPrice' => 2600,
                'original_price' => 2600,
                'discount' => 28,
                'rating' => 4.7,
                'reviews' => 84,
                'image' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80',
                'inStock' => 7,
                'stock' => 7,
                'totalStock' => 30,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Stretch cotton twill chinos with clean front pockets and ergonomic fit.'
            ],
[
                'id' => 'f9',
                'sku' => 'SKU-HOME-009',
                'barcode' => '880910000009',
                'name' => 'Stainless Steel Vacuum Thermal Flask 1000ml',
                'title' => 'Stainless Steel Vacuum Thermal Flask 1000ml',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 1450,
                'supplierCost' => 943,
                'oldPrice' => 2100,
                'original_price' => 2100,
                'discount' => 31,
                'rating' => 4.8,
                'reviews' => 135,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
                'inStock' => 10,
                'stock' => 10,
                'totalStock' => 35,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => '24-hour heat and cold retention double-wall vacuum insulated flask.'
            ],
[
                'id' => 'f10',
                'sku' => 'SKU-LAPT-010',
                'barcode' => '880910000010',
                'name' => 'RGB Gaming Mechanical Mouse 7200DPI',
                'title' => 'RGB Gaming Mechanical Mouse 7200DPI',
                'category' => 'laptops-computers',
                'category_id' => 'laptops-computers',
                'categoryName' => 'Laptops & Computers',
                'price' => 1690,
                'supplierCost' => 1099,
                'oldPrice' => 2400,
                'original_price' => 2400,
                'discount' => 29,
                'rating' => 4.8,
                'reviews' => 192,
                'image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
                'inStock' => 16,
                'stock' => 16,
                'totalStock' => 45,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Customizable RGB lighting zones with high-precision optical sensor.'
            ],
[
                'id' => 'f11',
                'sku' => 'SKU-HOME-011',
                'barcode' => '880910000011',
                'name' => 'Non-Stick Aluminium Frying Pan 28cm',
                'title' => 'Non-Stick Aluminium Frying Pan 28cm',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 2350,
                'supplierCost' => 1528,
                'oldPrice' => 3400,
                'original_price' => 3400,
                'discount' => 30,
                'rating' => 4.7,
                'reviews' => 78,
                'image' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=600&q=80',
                'inStock' => 12,
                'stock' => 12,
                'totalStock' => 40,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Heavy-gauge forged aluminium pan with ergonomic stay-cool handle.'
            ],
[
                'id' => 'f12',
                'sku' => 'SKU-SPOR-012',
                'barcode' => '880910000012',
                'name' => 'Lightweight Breathable Running Shoes',
                'title' => 'Lightweight Breathable Running Shoes',
                'category' => 'sports',
                'category_id' => 'sports',
                'categoryName' => 'Sports & Fitness',
                'price' => 2850,
                'supplierCost' => 1853,
                'oldPrice' => 4200,
                'original_price' => 4200,
                'discount' => 32,
                'rating' => 4.9,
                'reviews' => 210,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
                'inStock' => 6,
                'stock' => 6,
                'totalStock' => 25,
                'minStockThreshold' => 5,
                'section' => 'flash_sale',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Responsive foam cushioning with breathable knit mesh upper.'
            ],
[
                'id' => 'ft1',
                'sku' => 'SKU-SMAR-013',
                'barcode' => '880910000013',
                'name' => 'Sony WH-1000XM5 Noise-Canceling Headphones',
                'title' => 'Sony WH-1000XM5 Noise-Canceling Headphones',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 29999,
                'supplierCost' => 19499,
                'oldPrice' => 38999,
                'original_price' => 38999,
                'discount' => 23,
                'rating' => 4.9,
                'reviews' => 310,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
                'inStock' => 20,
                'stock' => 20,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'featured',
                'is_trending' => 1,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Premier active noise cancellation with speak-to-chat auto pause.'
            ],
[
                'id' => 'ft2',
                'sku' => 'SKU-HOME-014',
                'barcode' => '880910000014',
                'name' => 'Ergonomic Mesh High-Back Office Chair',
                'title' => 'Ergonomic Mesh High-Back Office Chair',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 13500,
                'supplierCost' => 8775,
                'oldPrice' => 17800,
                'original_price' => 17800,
                'discount' => 24,
                'rating' => 4.8,
                'reviews' => 88,
                'image' => 'https://images.unsplash.com/photo-1580481072645-022f9a6d1276?auto=format&fit=crop&w=600&q=80',
                'inStock' => 14,
                'stock' => 14,
                'totalStock' => 30,
                'minStockThreshold' => 5,
                'section' => 'featured',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => '3D adjustable armrests, lumbar support, and heavy-duty chrome wheelbase.'
            ],
[
                'id' => 'ft3',
                'sku' => 'SKU-LAPT-015',
                'barcode' => '880910000015',
                'name' => 'Asus ROG Strix Gaming Laptop 16-inch',
                'title' => 'Asus ROG Strix Gaming Laptop 16-inch',
                'category' => 'laptops-computers',
                'category_id' => 'laptops-computers',
                'categoryName' => 'Laptops & Computers',
                'price' => 185000,
                'supplierCost' => 120250,
                'oldPrice' => 199000,
                'original_price' => 199000,
                'discount' => 7,
                'rating' => 4.9,
                'reviews' => 140,
                'image' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80',
                'inStock' => 6,
                'stock' => 6,
                'totalStock' => 15,
                'minStockThreshold' => 5,
                'section' => 'featured',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'Intel Core i9 14th Gen, RTX 4070 Graphics, 240Hz ROG Nebula Display.'
            ],
[
                'id' => 'ft4',
                'sku' => 'SKU-LAPT-016',
                'barcode' => '880910000016',
                'name' => 'Mechanical RGB Backlit Gaming Keyboard',
                'title' => 'Mechanical RGB Backlit Gaming Keyboard',
                'category' => 'laptops-computers',
                'category_id' => 'laptops-computers',
                'categoryName' => 'Laptops & Computers',
                'price' => 5600,
                'supplierCost' => 3640,
                'oldPrice' => 7500,
                'original_price' => 7500,
                'discount' => 25,
                'rating' => 4.9,
                'reviews' => 240,
                'image' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
                'inStock' => 18,
                'stock' => 18,
                'totalStock' => 40,
                'minStockThreshold' => 5,
                'section' => 'featured',
                'is_trending' => 1,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Hot-swappable tactile switches with aluminum top frame and key macro software.'
            ],
[
                'id' => 'lt1',
                'sku' => 'SKU-ELEC-017',
                'barcode' => '880910000017',
                'name' => 'Samsung Galaxy S24 Ultra 5G (256GB)',
                'title' => 'Samsung Galaxy S24 Ultra 5G (256GB)',
                'category' => 'smartphones-gadgets',
                'category_id' => 'smartphones-gadgets',
                'categoryName' => 'Smartphones & Audio',
                'price' => 134999,
                'supplierCost' => 87749,
                'oldPrice' => 149999,
                'original_price' => 149999,
                'discount' => 10,
                'rating' => 4.9,
                'reviews' => 128,
                'image' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
                'inStock' => 10,
                'stock' => 10,
                'totalStock' => 25,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 0,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => false,
                'badge' => 'FEATURED',
                'description' => 'Titanium build with Snapdragon 8 Gen 3 for Galaxy and 100x zoom.'
            ],
[
                'id' => 'lt2',
                'sku' => 'SKU-HOME-018',
                'barcode' => '880910000018',
                'name' => 'Non-Stick Granite Cookware Set 5-Piece',
                'title' => 'Non-Stick Granite Cookware Set 5-Piece',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 7200,
                'supplierCost' => 4680,
                'oldPrice' => 9500,
                'original_price' => 9500,
                'discount' => 24,
                'rating' => 4.6,
                'reviews' => 62,
                'image' => 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
                'inStock' => 16,
                'stock' => 16,
                'totalStock' => 35,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'POPULAR',
                'description' => 'PFOA-free triple layer granite coating compatible with induction stovetops.'
            ],
[
                'id' => 'lt3',
                'sku' => 'SKU-FASH-019',
                'barcode' => '880910000019',
                'name' => 'Classic Vintage Leather Executive Wallet',
                'title' => 'Classic Vintage Leather Executive Wallet',
                'category' => 'mens-fashion',
                'category_id' => 'mens-fashion',
                'categoryName' => 'Men\'s Fashion',
                'price' => 1550,
                'supplierCost' => 1008,
                'oldPrice' => 2300,
                'original_price' => 2300,
                'discount' => 32,
                'rating' => 4.8,
                'reviews' => 104,
                'image' => 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
                'inStock' => 35,
                'stock' => 35,
                'totalStock' => 80,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Full-grain cowhide leather with RFID blocking lining and coin pocket.'
            ],
[
                'id' => 'lt4',
                'sku' => 'SKU-BEAU-020',
                'barcode' => '880910000020',
                'name' => 'Pure Organic Botanical Facial Serum 50ml',
                'title' => 'Pure Organic Botanical Facial Serum 50ml',
                'category' => 'beauty-care',
                'category_id' => 'beauty-care',
                'categoryName' => 'Beauty & Personal Care',
                'price' => 1350,
                'supplierCost' => 878,
                'oldPrice' => 1900,
                'original_price' => 1900,
                'discount' => 29,
                'rating' => 4.7,
                'reviews' => 89,
                'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
                'inStock' => 28,
                'stock' => 28,
                'totalStock' => 60,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'POPULAR',
                'description' => 'Cold-pressed botanical oils rich in Vitamin C for skin radiance.'
            ],
[
                'id' => 'lt5',
                'sku' => 'SKU-GROC-021',
                'barcode' => '880910000021',
                'name' => 'Premium Organic Extra Virgin Olive Oil 1L',
                'title' => 'Premium Organic Extra Virgin Olive Oil 1L',
                'category' => 'groceries',
                'category_id' => 'groceries',
                'categoryName' => 'Groceries & Daily Needs',
                'price' => 1850,
                'supplierCost' => 1203,
                'oldPrice' => 2200,
                'original_price' => 2200,
                'discount' => 16,
                'rating' => 4.9,
                'reviews' => 74,
                'image' => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
                'inStock' => 40,
                'stock' => 40,
                'totalStock' => 100,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 1,
                'is_flash_sale' => 1,
                'isTrending' => false,
                'isFeatured' => true,
                'isFlashSale' => true,
                'badge' => 'FLASH SALE',
                'description' => 'First cold-pressed Mediterranean olive oil rich in antioxidants and healthy fats.'
            ],
[
                'id' => 'lt6',
                'sku' => 'SKU-WOME-022',
                'barcode' => '880910000022',
                'name' => 'Women Designer Embroidered Silk Kurti',
                'title' => 'Women Designer Embroidered Silk Kurti',
                'category' => 'womens-fashion',
                'category_id' => 'womens-fashion',
                'categoryName' => 'Women\'s Fashion',
                'price' => 3450,
                'supplierCost' => 2243,
                'oldPrice' => 4800,
                'original_price' => 4800,
                'discount' => 28,
                'rating' => 4.8,
                'reviews' => 118,
                'image' => 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
                'inStock' => 14,
                'stock' => 14,
                'totalStock' => 35,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Handcrafted zari thread embroidery on soft Georgette silk fabric.'
            ],
[
                'id' => 'lt7',
                'sku' => 'SKU-HOME-023',
                'barcode' => '880910000023',
                'name' => 'Automatic Stainless Steel Espresso Coffee Maker',
                'title' => 'Automatic Stainless Steel Espresso Coffee Maker',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 14500,
                'supplierCost' => 9425,
                'oldPrice' => 18900,
                'original_price' => 18900,
                'discount' => 23,
                'rating' => 4.9,
                'reviews' => 112,
                'image' => 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=600&q=80',
                'inStock' => 9,
                'stock' => 9,
                'totalStock' => 25,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'POPULAR',
                'description' => '15-bar Italian pressure pump with milk frother wand.'
            ],
[
                'id' => 'lt8',
                'sku' => 'SKU-SMAR-024',
                'barcode' => '880910000024',
                'name' => 'Waterproof Sports Smartwatch Pro',
                'title' => 'Waterproof Sports Smartwatch Pro',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 4990,
                'supplierCost' => 3244,
                'oldPrice' => 6800,
                'original_price' => 6800,
                'discount' => 26,
                'rating' => 4.7,
                'reviews' => 143,
                'image' => 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
                'inStock' => 19,
                'stock' => 19,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'latest',
                'is_trending' => 0,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => false,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'POPULAR',
                'description' => 'GPS tracking, heart rate monitoring, and 14-day battery life.'
            ],
[
                'id' => 'tr1',
                'sku' => 'SKU-FASH-025',
                'barcode' => '880910000025',
                'name' => 'Slim Fit Designer Denim Jacket for Men',
                'title' => 'Slim Fit Designer Denim Jacket for Men',
                'category' => 'mens-fashion',
                'category_id' => 'mens-fashion',
                'categoryName' => 'Men\'s Fashion',
                'price' => 3100,
                'supplierCost' => 2015,
                'oldPrice' => 4200,
                'original_price' => 4200,
                'discount' => 26,
                'rating' => 4.8,
                'reviews' => 132,
                'image' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80',
                'inStock' => 19,
                'stock' => 19,
                'totalStock' => 45,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 1,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => true,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Heavyweight cotton denim with vintage wash and custom brass hardware.'
            ],
[
                'id' => 'tr2',
                'sku' => 'SKU-HOME-026',
                'barcode' => '880910000026',
                'name' => 'Minimalist Nordic Ceramic Coffee Mug Set',
                'title' => 'Minimalist Nordic Ceramic Coffee Mug Set',
                'category' => 'home-kitchen',
                'category_id' => 'home-kitchen',
                'categoryName' => 'Home & Appliances',
                'price' => 1890,
                'supplierCost' => 1229,
                'oldPrice' => 2600,
                'original_price' => 2600,
                'discount' => 27,
                'rating' => 4.9,
                'reviews' => 94,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
                'inStock' => 25,
                'stock' => 25,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Handcrafted stoneware ceramic mugs with matte glaze finish.'
            ],
[
                'id' => 'tr3',
                'sku' => 'SKU-LAPT-027',
                'barcode' => '880910000027',
                'name' => 'Wireless Ergonomic Vertical Mouse 2.4G',
                'title' => 'Wireless Ergonomic Vertical Mouse 2.4G',
                'category' => 'laptops-computers',
                'category_id' => 'laptops-computers',
                'categoryName' => 'Laptops & Computers',
                'price' => 1950,
                'supplierCost' => 1268,
                'oldPrice' => 2800,
                'original_price' => 2800,
                'discount' => 30,
                'rating' => 4.6,
                'reviews' => 168,
                'image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
                'inStock' => 30,
                'stock' => 30,
                'totalStock' => 70,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Reduces wrist strain with natural handshake grip position.'
            ],
[
                'id' => 'tr4',
                'sku' => 'SKU-BEAU-028',
                'barcode' => '880910000028',
                'name' => 'Hydrating Matte Velvet Lipstick Set',
                'title' => 'Hydrating Matte Velvet Lipstick Set',
                'category' => 'beauty-care',
                'category_id' => 'beauty-care',
                'categoryName' => 'Beauty & Personal Care',
                'price' => 2100,
                'supplierCost' => 1365,
                'oldPrice' => 2900,
                'original_price' => 2900,
                'discount' => 27,
                'rating' => 4.8,
                'reviews' => 210,
                'image' => 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80',
                'inStock' => 22,
                'stock' => 22,
                'totalStock' => 60,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Long-lasting transfer-proof color with moisturizing jojoba oil.'
            ],
[
                'id' => 'tr5',
                'sku' => 'SKU-SPOR-029',
                'barcode' => '880910000029',
                'name' => 'Adjustable Dumbbell Set 20kg Rubber Coated',
                'title' => 'Adjustable Dumbbell Set 20kg Rubber Coated',
                'category' => 'sports',
                'category_id' => 'sports',
                'categoryName' => 'Sports & Fitness',
                'price' => 6500,
                'supplierCost' => 4225,
                'oldPrice' => 8500,
                'original_price' => 8500,
                'discount' => 23,
                'rating' => 4.9,
                'reviews' => 79,
                'image' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
                'inStock' => 8,
                'stock' => 8,
                'totalStock' => 20,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 1,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => true,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Versatile home gym dumbbell set with anti-roll hexagonal plates.'
            ],
[
                'id' => 'tr6',
                'sku' => 'SKU-ELEC-030',
                'barcode' => '880910000030',
                'name' => 'Portable Mini Power Bank 20,000mAh 22.5W',
                'title' => 'Portable Mini Power Bank 20,000mAh 22.5W',
                'category' => 'smartphones-gadgets',
                'category_id' => 'smartphones-gadgets',
                'categoryName' => 'Smartphones & Audio',
                'price' => 2650,
                'supplierCost' => 1723,
                'oldPrice' => 3500,
                'original_price' => 3500,
                'discount' => 24,
                'rating' => 4.8,
                'reviews' => 189,
                'image' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&q=80',
                'inStock' => 35,
                'stock' => 35,
                'totalStock' => 80,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Fast charging dual USB-C ports with LED digital display.'
            ],
[
                'id' => 'tr7',
                'sku' => 'SKU-SMAR-031',
                'barcode' => '880910000031',
                'name' => 'Noise Cancelling True Wireless Earbuds',
                'title' => 'Noise Cancelling True Wireless Earbuds',
                'category' => 'smartwatches-audio',
                'category_id' => 'smartwatches-audio',
                'categoryName' => 'Smartwatches & Audio',
                'price' => 3490,
                'supplierCost' => 2269,
                'oldPrice' => 4800,
                'original_price' => 4800,
                'discount' => 27,
                'rating' => 4.9,
                'reviews' => 215,
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
                'inStock' => 18,
                'stock' => 18,
                'totalStock' => 50,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 1,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => true,
                'badge' => 'TRENDING',
                'description' => 'Active noise cancellation with 32h playback and IPX5 resistance.'
            ],
[
                'id' => 'tr8',
                'sku' => 'SKU-FASH-032',
                'barcode' => '880910000032',
                'name' => 'Luxury Chronograph Mens Analog Watch',
                'title' => 'Luxury Chronograph Mens Analog Watch',
                'category' => 'mens-fashion',
                'category_id' => 'mens-fashion',
                'categoryName' => 'Men\'s Fashion',
                'price' => 5200,
                'supplierCost' => 3380,
                'oldPrice' => 7200,
                'original_price' => 7200,
                'discount' => 28,
                'rating' => 4.8,
                'reviews' => 162,
                'image' => 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80',
                'inStock' => 12,
                'stock' => 12,
                'totalStock' => 30,
                'minStockThreshold' => 5,
                'section' => 'trending',
                'is_trending' => 1,
                'is_featured' => 0,
                'is_flash_sale' => 0,
                'isTrending' => true,
                'isFeatured' => false,
                'isFlashSale' => false,
                'badge' => 'TRENDING',
                'description' => 'Stainless steel case with Japanese quartz movement and sapphire glass.'
            ]
        ];

        foreach ($products as $prod) {
            DB::table('products')->updateOrInsert(['id' => $prod['id']], array_merge($prod, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }

        // 4. Seed Coupons
        $coupons = [
            [
                'id' => 'c_nexabd500',
                'code' => 'NEXABD500',
                'discountType' => 'flat',
                'discountValue' => 500.00,
                'discount_amount' => 500.00,
                'minSpend' => 4999.00,
                'usageLimit' => 100,
                'usageCount' => 12,
                'badge' => 'EXCLUSIVE FLASH PROMO',
                'headline' => 'Save ৳500 Instant Discount!',
                'subtext' => 'Enjoy ৳500 extra discount on your order when you spend ৳4,999+ with code NEXABD500.',
                'subtitle' => 'Enjoy ৳500 extra discount on your order when you spend ৳4,999+ with code NEXABD500.',
                'status' => 'ACTIVE',
                'is_active' => true
            ],
            [
                'id' => 'c_bikroy500',
                'code' => 'BIKROY500',
                'discountType' => 'flat',
                'discountValue' => 500.00,
                'discount_amount' => 500.00,
                'minSpend' => 3000.00,
                'usageLimit' => 100,
                'usageCount' => 8,
                'badge' => 'STORE COUPON',
                'headline' => 'Save ৳500 Instant Discount!',
                'subtext' => 'Enjoy ৳500 extra discount on your order when you spend ৳3,000+ with code BIKROY500.',
                'subtitle' => 'Enjoy ৳500 extra discount on your order when you spend ৳3,000+ with code BIKROY500.',
                'status' => 'ACTIVE',
                'is_active' => true
            ]
        ];

        foreach ($coupons as $c) {
            DB::table('coupons')->updateOrInsert(['id' => $c['id']], array_merge($c, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }

        // 5. Seed CMS Contents
        $heroSlides = [
            [
                'id' => 'slide-1',
                'title' => 'Sony WH-1000XM5 Wireless Headphones',
                'subtitle' => 'Industry-leading noise isolation with dual processors and 30-hour battery stamina.',
                'badge' => 'EXCLUSIVE LAUNCH 25% OFF',
                'badgeText' => 'EXCLUSIVE LAUNCH 25% OFF',
                'price' => '29,999',
                'oldPrice' => '38,999',
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=80',
                'active' => true
            ],
            [
                'id' => 'slide-2',
                'title' => 'Samsung Galaxy S24 Ultra 5G (256GB)',
                'subtitle' => 'Unleash Galaxy AI with 200MP Quad Telephoto and built-in S-Pen precision.',
                'badge' => 'SPECIAL PROMO DEAL',
                'badgeText' => 'SPECIAL PROMO DEAL',
                'price' => '134,999',
                'oldPrice' => '149,999',
                'image' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1600&q=80',
                'active' => true
            ]
        ];

        $mobileNavItems = [
            ['id' => 'home', 'label' => 'Home', 'icon' => 'Home', 'path' => '/', 'isSpecialBadge' => false, 'active' => true],
            ['id' => 'categories', 'label' => 'Categories', 'icon' => 'Grid', 'path' => '/categories', 'isSpecialBadge' => false, 'active' => true],
            ['id' => 'flash', 'label' => 'Flash Deals', 'icon' => 'Flame', 'path' => '#flash-sale', 'isSpecialBadge' => true, 'active' => true],
            ['id' => 'wishlist', 'label' => 'Wishlist', 'icon' => 'Heart', 'path' => '/wishlist', 'isSpecialBadge' => false, 'active' => true],
            ['id' => 'cart', 'label' => 'Cart', 'icon' => 'ShoppingBag', 'path' => '/cart', 'isSpecialBadge' => false, 'active' => true]
        ];

        $footerConfig = [
            'aboutText' => 'BikroyBD24 is your trusted online marketplace in Bangladesh offering authentic products, fast express delivery, and cash on delivery guaranteed.',
            'hotline' => '01854-288311',
            'supportEmail' => 'support@bikroybd24.com',
            'copyrightText' => '© 2026 BikroyBD24. All Rights Reserved.',
            'paymentBadges' => [
                'cod' => true,
                'bkash' => true,
                'nagad' => true,
                'rocket' => true,
                'visa' => true,
                'mastercard' => true
            ]
        ];

        DB::table('cms_contents')->updateOrInsert(['key' => 'hero_slides'], [
            'content' => json_encode($heroSlides),
            'created_at' => now(),
            'updated_at' => now()
        ]);

        DB::table('cms_contents')->updateOrInsert(['key' => 'mobile_nav_items'], [
            'content' => json_encode($mobileNavItems),
            'created_at' => now(),
            'updated_at' => now()
        ]);

        DB::table('cms_contents')->updateOrInsert(['key' => 'footer_info'], [
            'content' => json_encode($footerConfig),
            'created_at' => now(),
            'updated_at' => now()
        ]);
    }
}
